Post type setting field added
10up/gutenbridge pull request #104
Opened 2023-02-23 11:59 UTC by jayedul

### Description of the Change
As per current implementation, there is no way to resolve the issue other than explicitly adding `convert-to-blocks` support during custom post type registration. So, a new field added in writing setting page to enable/disable `Convert to Blocks` for specific post types without editing code.

Closes #57 

### How to test the Change

- Register custom post type
- Edit/create post
- Toggle the post type in writing setting page under `Convert to Blocks` section
- Check if Gutenberg editor gets enabled/disabled for that post type correctly

### Changelog Entry

> Added - Setting field added to enable/disable specific custom post type

### Credits

Props @jayedul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-02-28 14:53 UTC, Sidsector9 requested changes
@jayedul I am seeing the following error in the Settings > Writing page, can you have a look at it?

<img width="1714" alt="Screenshot 2023-02-28 at 6 01 58 PM" src="https://user-images.githubusercontent.com/17757960/221889994-f6899f83-f600-4ac4-a886-a741b2d6b337.png">

2023-03-13 11:22 UTC, Sidsector9 requested changes
<img width="409" alt="Screenshot 2023-03-13 at 4 45 10 PM" src="https://user-images.githubusercontent.com/17757960/224687136-a81d77f7-1347-437d-805b-e82ffdf404fe.png">

@jayedul let me know if I'm understanding this correctly. Should we limit the post types shown to only those that support the block editor? I don't think oEmbed responses, template parts, etc should be a part of this for the same reason.

If so, we can just the support using:

```php
if ( ! use_block_editor_for_post_type( $type ) ) {
	return;
}
```

Let me know what you think.

2023-03-13 14:24 UTC, jayedul commented
@Sidsector9 I added the checking initially. Then removed as it doesn't exclude all the unnecessary types. You can see in the screenshot before and after adding the check. 

<img width="1154" alt="Screenshot 2023-03-13 at 8 16 53 PM" src="https://user-images.githubusercontent.com/12506700/224729787-6945f502-ca0f-4669-8983-c088d0a3cbbf.png">

2023-03-21 15:40 UTC, Sidsector9 commented
@jayedul So I checked, and it seems that template parts, oEmbed does have support for the block editor.
However, I think we can still use `use_block_editor_for_post_type()` to remove the ones which don't have support.

2023-04-06 07:04 UTC, jayedul commented
@Sidsector9  Block editor check has been added. It can be re-reviewed though eslint test is failing here. There is no JS change in this PR, so I guess this issue is better to be fixed in a new ticket.

2023-04-11 11:52 UTC, Sidsector9 requested changes
@jayedul I am seeing fatal error when I save settings after unchecking all the checkboxes.

<img width="797" alt="Screenshot 2023-04-11 at 5 21 26 PM" src="https://user-images.githubusercontent.com/17757960/231154690-26bf113d-527a-4977-bd76-a8c791cd6127.png">

2023-05-03 08:32 UTC, jayedul commented
`in_array` check issue is fixed now. Re-review requested though eslint check is failing. Eslint issue is coming from another package `@10up/eslint-config`.
<img width="1161" alt="Screenshot 2023-05-03 at 2 29 14 PM" src="https://user-images.githubusercontent.com/12506700/235867242-59b4fb8b-bb4d-415f-b0fc-a37bb0d2b8d0.png">

2023-05-08 17:42 UTC, jeffpaul commented
@Sidsector9 back to you for review

2023-05-16 09:51 UTC, Sidsector9 approved these changes

2023-05-22 14:12 UTC, merged